name:                rule34-haskell
version:             0.1.0.0
github:              "githubuser/rule34-haskell"
license:             BSD3
author:              "2jacobtan"
maintainer:          "example@example.com"
copyright:           "2021 2jacobtan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rule34-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- jt2-haskell-utils
- containers
- pretty-simple
- split
- text
- fgl
- graphviz
- generic-data
- prettyprinter
- sbv
- casing
- mtl
- process
- svg-builder
- svg-builder-sandbox
- diagrams-sandbox
- optparse-generic

library:
  source-dirs: src

executables:
  rule34-org:
    main:                Main.hs
    source-dirs:         app/org
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rule34-haskell

  rule34-svg:
    main:                Main.hs
    source-dirs:         app/svg
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rule34-haskell

  rule34-png:
    main:                Main.hs
    source-dirs:         app/png
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rule34-haskell

tests:
  rule34-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rule34-haskell
