name:                mp
version:             0.1.0.0
github:              "mengwong/mp"
license:             BSD3
author:              "Wong Meng Weng"
maintainer:          "mwwong@smu.edu.sg"
copyright:           "2020"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mengwong/mp#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- text
- hspec
- megaparsec
- hspec-megaparsec
- mtl
- cassava
- vector
- bytestring
- pretty-simple
- boxes
- anyall
- split
- generic-data
- parsers
- aeson
- aeson-pretty
- utf8-string
- gf
- gf-ud
- typed-process
- stm
- replace-megaparsec
- extra

ghc-options: -Wall

library:
  source-dirs: src

executables:
  mp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mp

tests:
  mp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mp
