#+TITLE: throwaway experiments in petri net, process algebra, other workflow modeling

* Formalisms Considered

- Petri Nets
- BPMN
- Hierarchical State Machines (Harel State Charts)
- Concurrency
- Parallelism
- Continuations
- Process Algebras
  - CSP
  - CCP
  - pi-calculi

* Application Usages

** Flood & Goodenough

https://link.springer.com/epdf/10.1007/s10506-021-09300-9?sharing_token=M0oIt9b1RkTRd7yIGOhmRPe4RwlQNchNByi7wbcMAY47UEgYKTsS2y3NlCtlyjIQHDJKh4e6n-UgpQaxlMnNJsFMhDWtYOYhQkbOjngvwNEEMJPQBtf7qIAWYSNhod_xsaNwV_M_iCkxacdm-fOI3OAcRHGUt-KLIrxr0-B84xk%3D

On the main track, the loan is repaid in two halves.

On the auxiliary track, the borrower has to remain compliant with a number of property assertions. If the borrower fails to do so, the full balance of the loan is immediately due.

Those property assertions are represented as subcontracts, as they are not simple events but involve reparation pathways.


#+begin_example
  -------------------------------------
  | TrackMain                         |
  |                                   |
  |   --------------------------      |
  |   | FundsRequest           |      |
  |   --------------------------      |
  |     |                             |
  |     v                             |
  |   --------------------------      |
  |   | PrincipalLoan          |      |
  |   --------------------------      |
  |     |                             |
  |     v                             |
  |   --------------------------      |
  |   | FirstHalf              |      |
  |   --------------------------      |
  |     |                             |
  |     v                             |
  |   --------------------------      |
  |   | SecondHalf             |      |
  |   --------------------------      |
  |     |                             |
  |     v                             |
  |    fulfilled                      |
  |                                   |
  |------------------------------------ 
                | interrupt -- this is a hierarchical state machine arrow between boxes
                v 
           ------------------------
           | AcceleratedRepayment |
           ------------------------
#+end_example

and here's what the L4 could look like

#+begin_example

  DEFINE F&G
   MEANS Borrower Requests Principal
    THEN Lender Sends Principal
    THEN GUARD MainTrack
           AND SideTrack
          LEST Accelerate Repayment

       § MainTrack
  DEFINE MainTrack
   MEANS Debt 1
    THEN Debt 2

       § Borrower Requests Principal
   PARTY Borrower
     MAY NOTIFY Lender
                  with :  reqAmount :: Money

       § Lender Sends Principal
   PARTY Lender
    MUST send funds
                    to :  Borrower
             principal := reqAmount
           outstanding := principal * 1.075

       § Debt 1
   PARTY Borrower
   AFTER 1 year
    MUST repay first half
                    to :  Lender
                amount :  principal * 0.550
           outstanding := outstanding * 0.525

       § Debt 2
   PARTY Borrower
   AFTER 1 year
    MUST repay second half
                    to :  Lender
                amount :  outstanding
           outstanding := 0
   HENCE FULFILLED

       § SideTrack
   PARTY Lender
     MAY NOTIFY Borrower
                    of : defaultEvent :: eventDetails
   HENCE    PARTY Borrower
           WITHIN 2 days
             MUST notify Lender
                  that : defaultEvent is cured

      // upon reaching BREACH state in the GUARDed section
       § Accelerate Repayment
   PARTY Borrower
    MUST pay
                    to : Lender
                amount : outstanding
  WITHIN 1 day

#+end_example

What happens when multiple defaults occur? The source contract says "In the event of multiple events of default, the ﬁrst to occur shall take precedence for the purposes of specifying outcomes under this agreement."

** The GUARD keyword

Allows thread termination by another thread by draining the guard.

The guard is automatically filled when a GUARD scope is entered, and automatically drained by any thread that leaves the GUARD scope.

In the contract above, failure to repay Debt 1 or Debt 2 (on the main track), or failure to cure a default (on the side track) leads to BREACH; which then leads to the "Accelerate Repayment" clause.

** Modeling as a Petri Net

\begin{equation}
e^{\pi i} + 1 = 0
\end{equation}

Modeling Termination

** PDPA DBNO

** The SAFE




