#+TITLE: throwaway experiments in petri net, process algebra, other workflow modeling

* Formalisms Considered

- Petri Nets
- BPMN
- Hierarchical State Machines (Harel State Charts)
- Concurrency
- Parallelism
- Continuations
- Process Algebras
  - CSP
  - CCP
  - pi-calculi

* Application Usages

** Flood & Goodenough

https://link.springer.com/epdf/10.1007/s10506-021-09300-9?sharing_token=M0oIt9b1RkTRd7yIGOhmRPe4RwlQNchNByi7wbcMAY47UEgYKTsS2y3NlCtlyjIQHDJKh4e6n-UgpQaxlMnNJsFMhDWtYOYhQkbOjngvwNEEMJPQBtf7qIAWYSNhod_xsaNwV_M_iCkxacdm-fOI3OAcRHGUt-KLIrxr0-B84xk%3D

On the main track, the loan is repaid in two halves.

On the auxiliary track, the borrower has to remain compliant with a number of property assertions. If the borrower fails to do so, the full balance of the loan is immediately due.

Those property assertions are represented as subcontracts, as they are not simple events but involve reparation pathways.


#+begin_example
  -------------------------------------
  | TrackMain                         |
  |                                   |
  |   --------------------------      |
  |   | FundsRequest           |      |
  |   --------------------------      |
  |     |                             |
  |     v                             |
  |   --------------------------      |
  |   | PrincipalLoan          |      |
  |   --------------------------      |
  |     |                             |
  |     v                             |
  |   --------------------------      |
  |   | FirstHalf              |      |
  |   --------------------------      |
  |     |                             |
  |     v                             |
  |   --------------------------      |
  |   | SecondHalf             |      |
  |   --------------------------      |
  |     |                             |
  |     v                             |
  |    fulfilled                      |
  |                                   |
  |------------------------------------ 
                | interrupt -- this is a hierarchical state machine arrow between boxes
                v 
           ------------------------
           | AcceleratedRepayment |
           ------------------------
#+end_example

and here's what the L4 could look like

#+begin_example
  DEFINE F&G
   MEANS TrackMain
     AND TrackAuxiliary

       § TrackMain
  DEFINE TrackMain
   MEANS FundsRequest
    THEN PrincipalLoan
    THEN FirstHalf
    THEN SecondHalf

       § FundsRequest
   PARTY Borrower
     MAY NOTIFY Lender
                  with = reqAmount :: Money

       § PrincipalLoan
   PARTY Lender
    MUST send funds
                    to = Borrower
             principal := reqAmount
           outstanding := principal * 1.075

       § FirstHalf
   PARTY Borrower
   AFTER 1 year
    MUST repay first half
                    to = Lender
                amount = principal * 0.550
           outstanding := outstanding * 0.525

       § SecondHalf
   PARTY Borrower
   AFTER 1 year
    MUST repay second half
                    to = Lender
                amount = outstanding
           outstanding := 0

       § TrackAuxiliary
   PARTY Borrower
    MUST avoid default
   UNTIL Termination
    LEST   PARTY Lender
             MAY notify Borrower
                     of = msgBody :: eventDetails
           HENCE    PARTY Borrower
                   WITHIN 2 days
                     MUST cure default
                      AND notify Lender
                          that = default is cured
                     LEST  INTERRUPT TrackMain -- note scope hierarchy
                                 AND PARTY Borrower
                                      MUST accelerate repayment
                                               to = Lender
                                           amount = outstanding
#+end_example

What happens when multiple defaults occur? The source contract says "In the event of multiple events of default, the ﬁrst to occur shall take precedence for the purposes of specifying outcomes under this agreement."

** 

** PDPA DBNO

** The SAFE




