package cpp.Absyn; // Java Package generated by the BNF Converter.

public sealed interface Def permits DFun{
    interface Visitor<R, A> {
        R visit(cpp.Absyn.DFun p, A arg);
    }

    <R, A> R accept(cpp.Absyn.Def.Visitor<R, A> v, A arg);
}