package cpp.Absyn; // Java Package generated by the BNF Converter.

public record DFun(Type type, String id, ListArg args, ListStm statements)  implements Def {
  @Override
  public <R, A> R accept(Visitor<R, A> v, A arg) {
    return v.visit(this, arg);
  }
}
