package cpp.Absyn; // Java Package generated by the BNF Converter.

public record EAnd(Exp exp_1, Exp exp_2) implements Exp{
    @Override
    public <R, A> R accept(Visitor<R, A> v, A arg) {
        return v.visit(this, arg);
    }
}
