package cpp.Absyn; // Java Package generated by the BNF Converter.

public class EApp  extends Exp {
  public final String id_;
  public final ListExp listexp_;
  public EApp(String p1, ListExp p2) { id_ = p1; listexp_ = p2; }

  public <R,A> R accept(cpp.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof cpp.Absyn.EApp) {
      cpp.Absyn.EApp x = (cpp.Absyn.EApp)o;
      return this.id_.equals(x.id_) && this.listexp_.equals(x.listexp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.id_.hashCode())+this.listexp_.hashCode();
  }


}
