package cpp.Absyn; // Java Package generated by the BNF Converter.

public class ETyped  extends Exp {
  public final Exp exp_;
  public final Type type_;
  public ETyped(Exp p1, Type p2) { exp_ = p1; type_ = p2; }

  public <R,A> R accept(cpp.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof cpp.Absyn.ETyped) {
      cpp.Absyn.ETyped x = (cpp.Absyn.ETyped)o;
      return this.exp_.equals(x.exp_) && this.type_.equals(x.type_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.exp_.hashCode())+this.type_.hashCode();
  }


}
