package cpp.Absyn; // Java Package generated by the BNF Converter.

public class SBlock  extends Stm {
  public final ListStm liststm_;
  public SBlock(ListStm p1) { liststm_ = p1; }

  public <R,A> R accept(cpp.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof cpp.Absyn.SBlock) {
      cpp.Absyn.SBlock x = (cpp.Absyn.SBlock)o;
      return this.liststm_.equals(x.liststm_);
    }
    return false;
  }

  public int hashCode() {
    return this.liststm_.hashCode();
  }


}
