package cpp.Absyn; // Java Package generated by the BNF Converter.

public record SExp(Exp exp) implements Stm {
    public <R, A> R accept(cpp.Absyn.Stm.Visitor<R, A> v, A arg) {
        return v.visit(this, arg);
    }
}
