package cpp.Absyn; // Java Package generated by the BNF Converter.

public record SIfElse(Exp exp, Stm stm_1, Stm stm_2)  implements Stm {
  public <R,A> R accept(cpp.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }
}
