package cpp.Absyn; // Java Package generated by the BNF Converter.

public interface Stm {
    <R, A> R accept(Stm.Visitor<R, A> v, A arg);

    interface Visitor<R, A> {
        R visit(cpp.Absyn.SExp p, A arg);

        R visit(cpp.Absyn.SDecls p, A arg);

        R visit(cpp.Absyn.SInit p, A arg);

        R visit(cpp.Absyn.SReturn p, A arg);

        R visit(cpp.Absyn.SReturnVoid p, A arg);

        R visit(cpp.Absyn.SWhile p, A arg);

        R visit(cpp.Absyn.SBlock p, A arg);

        R visit(cpp.Absyn.SIfElse p, A arg);
    }

}
