package cpp.Absyn; // Java Package generated by the BNF Converter.

public abstract class Stm implements java.io.Serializable {
  public abstract <R,A> R accept(Stm.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(cpp.Absyn.SExp p, A arg);
    public R visit(cpp.Absyn.SDecls p, A arg);
    public R visit(cpp.Absyn.SInit p, A arg);
    public R visit(cpp.Absyn.SReturn p, A arg);
    public R visit(cpp.Absyn.SReturnVoid p, A arg);
    public R visit(cpp.Absyn.SWhile p, A arg);
    public R visit(cpp.Absyn.SBlock p, A arg);
    public R visit(cpp.Absyn.SIfElse p, A arg);

  }

}
