package cpp.Absyn; // Java Package generated by the BNF Converter.

public record Type_double() implements Type {
    @Override
    public <R, A> R accept(Visitor<R, A> v, A arg) {
        return v.visit(this, arg);
    }
}
