package cpp.Absyn; // Java Package generated by the BNF Converter.

public class Type_void  extends Type {
  public Type_void() { }

  public <R,A> R accept(cpp.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof cpp.Absyn.Type_void) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
