package cpp.Absyn; // Java Package generated by the BNF Converter.

import cpp.TypeCode;

public interface Type {
    <R, A> R accept(cpp.Absyn.Type.Visitor<R, A> v, A arg);
    TypeCode getTypeCode();

    interface Visitor<R, A> {
        R visit(cpp.Absyn.Type_bool p, A arg);

        R visit(cpp.Absyn.Type_int p, A arg);

        R visit(cpp.Absyn.Type_double p, A arg);

        R visit(cpp.Absyn.Type_void p, A arg);

        R visit(cpp.Absyn.Type_string p, A arg);
    }

}
