package cpp.Absyn; // Java Package generated by the BNF Converter.

import cpp.TypeCode;

public record Type_int() implements Type {
    @Override
    public <R, A> R accept(Visitor<R, A> v, A arg) {
        return v.visit(this, arg);
    }

    @Override
    public TypeCode getTypeCode() {
        return TypeCode.CInt;
    }
}
