resolver: lts-20.2

packages:
- .

# so that `stack build --copy-bins` puts bin here
local-bin-path: .

extra-deps:
# - github: GrammaticalFramework/gf-core
#   commit: d06539c # release 3.10
- gf-3.10
- cgi-3001.3.0.3 # dependency of gf

flags:
     # this excludes PGF2 module in gf package
  gf:
    c-runtime: false