load ./verification/model-check  

(rewrite [1]
  start

  < 'lender : Actor | none > 
  < 'borrower : Actor | none >

  < 'state : SimulationState |
    time : (T:Time),
    rules : (Rs0:Set{Rule}),
    activeRules : (
      PARTY 'borrower MUST DO 'pay_payment WITHIN (T0:Time),
      PARTY 'borrower SHANT DO 'default WITHIN (T1:Time)
    ),
    remainingTrace :
      ('borrower does 'pay_payment) ++
      ('borrower does 'default)
  >
.)

eof

(reduce
  modelCheck(none, [] Top)
.)