name:                hxtfun
version:             0.1.0.0
github:              "githubuser/hxtfun"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hxtfun#readme>

dependencies:
- base >= 4.7 && < 5
- hxt
- hxt-css
- hxt-curl

library:
  source-dirs: src

executables:
  hxt-write:
    main:                Main.hs
    source-dirs:         app/write
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hxtfun

  hxt-read:
    main:                Main.hs
    source-dirs:         app/read
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hxtfun

tests:
  hxtfun-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hxtfun
