name:                parse-predicates
version:             0.1.0.0
#github:              "https://github.com/smucclaw/sandbox/tree/default/inari/rps"
license:             BSD3
author:              "Inari Listenmaa"
maintainer:          "inari.listenmaa@gmail.com"
copyright:           "2021 Inari Listenmaa"
build-type:          "Custom"

custom-setup:
  dependencies: 
  - base >= 4.7 && < 5
  - Cabal >= 1.10
  - filepath

extra-source-files:
# - README.md
- grammars/Parse.gf


# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rps#readme>

dependencies:
- base >= 4.7 && < 5
- gf
- split
- extra
- mtl
- containers

ghc-options:
- -Wall
- -Wno-unticked-promoted-constructors

internal-libraries:
  gf-generated:
    exposed-modules:
    - Parse
    source-dirs:
    - grammars

library:
  dependencies:
  - gf-generated
  source-dirs: 
  - src


executables:
  rps-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parse-predicates
