resolver: lts-16.20

packages:
  - .

extra-deps:
  - github: GrammaticalFramework/gf-core
    commit: 7dc6717b5e95122a810d3b580981fc4ce0c9744b
  - json-0.10@sha256:d9fc6b07ce92b8894825a17d2cf14799856767eb30c8bf55962baa579207d799,3210

#Required for the option custom-preprocessor-extensions
# require-stack-version: ">= 2.6.0"
#This will show a warning
custom-preprocessor-extensions:
- gf

flags:
  # this excludes PGF2 module in gf package
  gf:
    c-runtime: false
    server: false
