load abstract-machine

(smod INTERPRETER is
  protecting ABSTRACT-MACHINE + EVENT-TRACE .

  strat rewriteAlongTrace : EventTrace @ Configuration .

  vars actorName actionName : Oid . 
  vars events : EventTrace .

  sd rewriteAlongTrace(emptyEventTrace) := idle .

  sd rewriteAlongTrace((actorName does actionName) events) :=
    event[actorName <- actorName, actionName <- actionName] ;
    rewriteAlongTrace(events) .

endsm)