name:                haskell-toys
version:             0.1.0.0
github:              "anka-213/haskell-toys"
license:             BSD3
author:              "Andreas Källberg"
maintainer:          "anka.213@gmail.com"
copyright:           "(c) 2019 Andreas Källberg"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/anka-213/haskell-toys#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- prettyprinter
- bound
- deriving-compat
- random
- profunctors
- process
- turtle

library:
  source-dirs: src

executables:
  haskell-toys-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-toys

tests:
  haskell-toys-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-toys
