package sg.edu.smu.cclaw.calc.Absyn; // Java Package generated by the BNF Converter.

public abstract class Exp implements java.io.Serializable {
  public abstract <R,A> R accept(Exp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(EAdd p, A arg);
    public R visit(ESub p, A arg);
    public R visit(EMul p, A arg);
    public R visit(EDiv p, A arg);
    public R visit(EInt p, A arg);

  }

}
