fmod QNA is
  sort Answer .
  ops Yes No : -> Answer .

  ops correct wrong : -> CorrectWrong .
  subsort CorrectWrong < Bool .

  op _ to say : CorrectWrong -> Bool .

  eq correct = true .
  eq wrong = false .

  vars bool bool' : Bool .

  eq bool to say = bool .

  op Is it _ that _ ? : Bool Bool -> Answer .

  eq Is it bool that bool ? = Yes .
  eq Is it bool that bool' ? = No [owise] .

endfm